### ISSUE TITLE
move Hiding* from kyber pkg to curve25519 pkg

### ISSUE THREAD

**Issue by ineiti** [dedis/kyber#204] opened 2017-08-14 07:01 UTC
From @bford 
* I'm thinking that the Hiding interface hack perhaps should just be merged into the Point interface, since (a) it's increasingly generally useful and applicable to many types of curves, and (b) not all methods in the Point interface actually work with all possible curves anyway either.  

* Also, if it's true - as has been suggested at least - that using an Elligator-type injective map is generally a faster/better way to pick random hash-points than the "sample and retry" method the library currently uses, then perhaps the Pick() and HideDecode() methods are redundant and should be merged somehow?

From @nikkolasg 
I would advise against merging that with the `Point` interface because 1) it's already overloaded in my opinion and 2) not all curves supports this hiding interface right ? I only know of Elligator mappings.... Seems it's one of the properties we can ask for a Group, like "can you create hiding points?". It's the same story for bilinear mappings, "can you create a bilinear mapping?". 
Not going to the full `GroupProperty` approach, what about:
```go
if group.SupportHiding() {
  hidden = myPoint.(Hiding)
  ...
}
```

**Comment by ineiti** [comment] 2017-08-14 07:20
If we can merge `Pick` and `HideDecode`, this would be best. Then, if the group supports a `Hiding` way of picking the point, it implements it. Else, `Pick` does the same as it does now.

**Comment by nikkolasg** [comment] 2017-08-22 09:08
@ineiti I guess you mean `HideEncode`. I like the idea of merging `Pick` and `HideEncode` using the best algorithm available. One question remains though is what to do with `HideDecode`. 
Shall we integrate this into the `Point` interface ? I'm still on the fence about this, and would prefer to keep the interface separated instead of overloading the `Point` interface, which is already quite large. Again from my experience writing the wrapper around the PBC code from dfinity, I had to `panic` on these kinds of methods because it's just not possible to do this on every group/curves, so I'm not sure it's a good idea to have a large interface with many methods "optional" which may panic...

**Comment by ineiti** [comment] 2017-08-22 10:43
Looking through the code, we have a lot of ways to create a `Point`:
0. `Set` - copies from another point
1. `SetInt64` - sets to a small 64-bit integer value
2. `Pick` - is mostly used for a random points
3. `SetBytes` - copies a full byte-slice and does the modulo
4. `Embed` - encodes some bytes of data
5. `HideEncode` - Aligator-encrypt some bytes of data

For decoding, we have:
0., 1., 2., none
3. `Bytes` - the modulo of the data
4. `Data` - retrieves the data set with `Embed`
5. `HideDecode` - retrieves the data set with `HideEncode`

So if we merge, it would be merging of:
merge `Embed` and `HideEncode`
merge `Data` and `HideDecode`

Now I think I got it right - I hope ;) This would get rid of `Hide{En,De}code`.

What about `SetInt64`, `SetBytes` and `Pick`? At least `SetInt64` and `SetBytes` seem valid candidates for merging, too. Probably not `Pick`, though.

**Comment by nikkolasg** [comment] 2017-08-22 10:47
> merge Data and HideDecode
I don't think they can merge as they have different purposes. `Data` is to retrieve a small slice of bytes from a `Point`. `HideDecode` is to create a point from a random looking slice of bytes.

**Comment by nikkolasg** [comment] 2017-08-22 11:52
Also there's no `SetInt64` for`Point`, only for `Scalar`

**Comment by ineiti** [comment] 2017-08-22 13:45
true. So now I only have to understand the difference between `HideEncode` and `HideDecode`.

I'm starting to run in circles: why did we separate `Pick` and `Embed` in `v1`? As far as I can see, in `v0` they were in one function...

**Comment by ineiti** [comment] 2017-08-23 12:33
OK, after talking with @bford I finally see the light: 

* `HideEncode` is like `Marshal`, but it can fail
* `HideDecode` is like `Unmarshal`, but it will never fail

So `HideDecode` can replace `Pick`, but `HideEncode` cannot replace `Embed`.

**Comment by bford** [comment] 2017-08-23 13:26
Thinking about possible better names for HideEncode and HideDecode, what about:

- HideDecode -> Pick (i.e., combine HideEncoede into Pick; this becomes the standard hash-to-Point mechanism)
- HideEncode -> UnPick (i.e., try to find an input to Pick that will reproduce the given Point; this attempt may fail since not all Points may be representable in the injective mapping)
- HideLen -> PickLen (i.e., return the number of bytes required and consumed by Pick)

?

**Comment by bford** [comment] 2017-08-23 13:35
In terms of further naming clarifications, I'm thinking maybe we should rename Embed to EmbedData, so that it's more clear from the names that Data and EmbedData are a pair that go together (just like Marshal/Unmarshal and Pick/UnPick).  Perhaps even rename Data to ExtractData or GetData as well.  Less concise but maybe more clear.

**Comment by bford** [comment] 2017-08-23 13:41
Perhaps a more concise but equally clear naming alternative to "EmbedData/ExtractData" would be "PutData/GetData"?

**Comment by ineiti** [comment] 2017-08-25 06:06
Summarizing:
* `Pick([]byte)kyber.Point` (former HideDecode, succeeds always - two inputs might have the same output)
* `UnPick(kyber.Point)([]byte, error)` (former HideEncode, can fail 
  * `Pick( Unpick ( x ) ) == x` holds if `Unpick(x)` doesn't fail
  * `Unpick( Pick( d ) ) == d` doesn't always hold, but should never fail
* `PutData([]byte)(kyber.Point, []byte)` (former Embed)
* `GetData(kyber.Point)[]byte` (former Data)

**Comment by nikkolasg** [comment] 2017-08-25 07:13
Where to put the randomness  `cipher.Stream` that we had before in the `Pick` operation ? (and in the `Embed` ?) 
We had some cases where it's needed.

**Comment by ineiti** [comment] 2017-08-25 07:27
I updated the summary - is it better now?

**Comment by bford** [comment] 2017-08-26 09:37
I don't think the Pick method needs the first []byte parameter anymore, since that was only for the optional Embed functionality wasn't it?  (which is now handled by PutData)

Also, don't forget the corresponding Len methods: PickLen, DataLen, MarshalLen?  (I guess the latter is currently called MarshalSize; would marshalLen be more consistent with Go naming conventions?)

Also, the Len topic brings up another issue again (I think maybe we discussed this before): should Group include the PointLen/ScalarLen methods, or would it be better for callers wanting the appropriate lengths just to do Point().MarshalLen() or Scalar().MarshalLen()?  Of course that's slightly more cumbersome and less efficient for client code that doesn't already have an appropriate Point or Scalar object lying around, but I'd wager that's probably not all that common.  Perhaps more importantly, having Group methods named PointLen and ScalarLen seems to imply that there is only one kind of "length" important for Point and Scalar objects, which as has become clear above is clearly false: there are at least three lengths of relevance (with very different meanings) - the marshaling length, the embeddable data length, and the injective-map (Pick) input length.  So this is making me think that the slight convenience of having the (marshalling) length methods in the Group is not worth the potential cost in terms of potential confusion about *which* length those Group methods return.  What do you think?

**Comment by bford** [comment] 2017-08-26 09:40
Also, a really nitpicky capitalization detail: @ineiti I see you used both "UnPick" and "Unpick" in the summary; of course we have to decide on one of the two capitalizations.  I'm leaning toward "Unpick", first for consistency with the existing "Unmarshal" (which isn't "UnMarshal"), and second because of laziness, i.e., typing it requires pressing the shift key one fewer times. :)

**Comment by bford** [comment] 2017-08-26 09:46
Ah, maybe I was wrong above about Pick not needing its first argument: if your intent was for Pick's first argument to be its "primary" input (of length PickLen), and not a now-irrelevant "embedding data" argument, then that first argument is clearly needed.  But in that case that raises the question of whether the second (cipher.Stream) argument is still needed.  If we're requiring all curves supported under this framework to have Elligator-style injective maps of some kind, in my understanding those maps are and must be deterministic, and hence shouldn't ever need a ransomness input at all.  (PutData for data embedding still does need a randomness input, but I don't think Pick should.)  Is this reasoning correct or am I missing something?

**Comment by nikkolasg** [comment] 2017-08-26 17:53
> if your intent was for Pick's first argument to be its "primary" input (of length PickLen)

Yes.
`Pick`'s main usage is to create a random Point (without knowing its secret pre-image), hence that is the main use of the `cipher.Stream`.  So indeed you 're right in the sense that *if we require* all curves to have Elligator-style injective maps, then we can remove the `cipher.Stream` argument.
In my opinion, that requirement is way too strict: I only know ed25519 (and Ed448) which fulfill this requirement. I don't know for sure but I have strongs doubts that the NIST curves and the pairing based curves provide that as well. In the end, most of our practical implementations of these functions will have to panic as 1) it just don't work, or 2) it's not possible to "guess" a probable point without introducing randomness.
Even though the new interfaces proposed look correct, it adds two new method to the current `Point` abstraction for a gain I'm failing to see... I would highly prefer a way to detect capabilities at runtime instead of forcing implementation details into the interface definition. 

> (b) not all methods in the Point interface actually work with all possible curves anyway either

That's exactly the issue we should try to resolve in my opinion :) We should try to reduce `Point` to a minumum (using a possible `Element` for example !) and be able to let users decide what capabilities to use while still keeping new implementations clean and concise implementing only what it can do. For example, inspiring from the "user choose Suite's capabilities" new design:
```go
type MyEd25519Point interface{
    Element
    Hiding
    DataStore // for example: `PutData` & `GetData`
}
```
See Spf13's slide 34 on his [common go mistakes](http://spf13.com/presentation/7-biggest-mistakes-in-go/).

**Comment by bford** [comment] 2017-08-28 14:38
While Elligator itself is restricted to certain curves, in my understanding, some of the follow-on work showed that equivalent mappings are feasible on a much wider class of curves (or perhaps all elliptic curves?).  See in particular "Binary Elligator Squared": https://hal.inria.fr/hal-01094083/document  For example, see the intro discussion on "admissible encodings", which are "known to exist for all isomorphism classes of elliptic curves".  

More generally, I agree that narrower, composable interfaces interfaces are generally preferable when practical.  It would especially be great if both 'Point' and 'Scalar' could be broken into (or derived from) a simple common 'Element' interface.  However, in my experience so far there are a bunch of downsides in practice.  

One downside is that you invariably end up having to do a lot more casting (or testing-and-casting), increasing the complexity of a lot of the code using the interfaces.  If we had a lot of different (types of) curves and many of them fundamentally couldn't support important subsets of the functionality we're talking about, then breaking out those optional functions into separate interfaces to be separately tested for and cast to.  (And perhaps it could be argued that Hiding may still be in that category - I'm not sure just how general the Elligator++ techniques above are.)  But most of the stuff the Point and Scalar interfaces cover I think are readily implementable in some fashion across practically all useful elliptic curves that I'm aware of, and also fairly generally useful for well-known purposes.

Another practical downside of breaking these into smaller interfaces is the "return type" problem.  Notice that many of the Scalar arithmetic methods are defined to return Scalar (the same one passed in, for convenience), and similarly many of the Point arithmetic methods return the same Point for convenience.  But in a broken-apart interface, the return types of the methods of the different interfaces can only return the type corresponding to the interface they're defined in, at best, and perhaps only the 'Element' base type.  More-specific operations like (for example) Div and Inv probably wouldn't be part of the basic Element interface since they're only meaningful for operations on scalars (i.e., fields as opposed to groups).  But since the type signature of basic operations like Add() will have to have the base Element as their return type, usage patterns like myscalar.Add(...).Div(...) won't work even though myscalar.Add(...) and myscalar.Div(...) work fine.  Nothing critical, but potentially annoying and confusing.  

An obvious way to "work around" this issue is simply to give up the programming convenience of having these methods have return values at all, in which all code would just have to do "myscalar.Add(...); myscalar.Div(...); etc", one operation at a time.  It's certainly a convenience we could live without, but I at least got to liking it while using Go's big.Int and such.  

Yet a third approach I've considered would be to have the generic interfaces be small and minimal and have no "convenience return values" at all, but then to define some barebones "wrapper types" around the interfaces - e.g., a struct containing nothing but a reference to a GroupElement or FieldElement interface - which in turn provide methods with the return-value convenience convention and perhaps other convenience methods added.  That may be still worth considering - I even started prototyping such a variant once - but never finished it and it proved to be an extremely invasive change.  So that's the problem.

**Comment by bford** [comment] 2017-08-28 15:24
To be more specific, one version of the third approach above I've thought about for a while is more-or-less as follows.

First, a set of small, modularized interfaces, e.g.:

type GroupElement interface {
  Add(a, b GroupElement) // note: NO convenience return values
  Sub(a, b GroupElement)
  ...
}

type FieldElement interface {
  GroupElement  // inherit group methods
  Mul(a, b FieldElement)
  Div(a, b FieldElement)
  ...
}

type Hiding interface { ... }
type DataEmbedding interface { ...}
...and so on, for whatever "modularized interfaces" we want.

Then we define convenience wrapper types around these interfaces in common, useful combinations.  For example, the current Scalar and Point might become convenience wrapper types rather than interfaces:

type Point struct {
  E GroupElement
}

type Scalar struct {
  E FieldElement
}

func (p Point) Add(a, b Point) Point {  // note: WITH convenience return values
  p.E.Add(a.E, b.E)
  return p
}

func (p Point) PutData(...) Point {
  p.E.(DataEmbedding).PutData(...) // dynamically cast to optional-functionality interface
  return p
}

This approach has at least one clear long-term advantage: we're much less likely to need to make changes to the modular barebones interfaces going forward, since instead we'd mostly just add new interfaces to support new/optional/improved functionality in a backward-compatible way.  And since the convenience wrappers like Point and Scalar are just regular struct types rather than interfaces themselves, we can more freely add new methods to these convenience wrappers (to get to the new/improved/optional functionality) without breaking backward compatibility with existing code.

Again, I'd been thinking about doing something like this for a while and even started a prototype implementation at some point, but never quite finished it.  I think I still have that in a branch somewhere, but not sure where.  If you like the idea of going in this direction, we could explore it - but of course it'll be another significant and not-entirely-painless change in the way of kyber.v1 :/  (On the other and it might not be too painful either; if Point and Scalar become convenience wrappers as suggest above then a lot of the existing code using them shouldn't have to be changed much.)

**Comment by ineiti** [comment] 2017-08-29 07:06
Reality-test: would this help with the pairing-based crypto?

**Comment by nikkolasg** [comment] 2017-08-29 08:13
> ```gofunc (p Point) PutData(...) Point {
>  p.E.(DataEmbedding).PutData(...) // dynamically cast to optional-functionality interface
>  return p
> }
```
I'm not sure we need to make the `Point` struct do that, why not let the user do it ? In most use cases, the user should not be able to continue with a non `DataEmbedding` point, because it's highly likely that his protocol can't continue. In these cases, I would prefer that the user does the check himself so when coding his protocol, he has to be aware of the fact that not all points implement it. 

> Reality-test: would this help with the pairing-based crypto?

The proposed approach in the issue adds new methods that will only panic in my pbc wrappers at least. This new method proposes to reduce the number of "panic" method the pbc wrapper has to write (`PutData` for example) and express clearly the basic functionalities of the pbc wrapper, limited for the moment compared to what Ed25519 can offer. 
I'm not sure which is the best way to handle this problem (I'll try to think about it more when I have "time")  but I feel like we're going more in the right direction.. !

**Comment by nikkolasg** [comment] 2017-09-08 08:50
So coming back after a while on this issue, I really like @bford 's proposal because it would directly alleviate the effort that one must do in order to implement a new group.
For example. with pbc, one just needs to implement the basic arithmetic methods and that's it. `Point.PutData` will panic but at least, it's not the responsability of the developer to implement all "panic-able" methods. 
And also the fact that it will be way more easy to extend that is a great bonus.
I'm all for it !

**Comment by jeffallen** [comment] 2017-11-09 11:08
At the meeting today, we agreed that the cost/benefit tradeoff to a radical change to kyber.{Scalar,Point,Group} is too much cost with not enough benefit at this point in the release cycle. Thus we will not attempt it.

We did not talk about the other questions about HideEncode/HideDecode. I propose to close this issue without changing anything, because it is an open question if all groups can do hiding, but even if they can, our current research interests do not seem to depend on this.

(I am actually closing this for now. If you really disagree, reopen it with your comment explaining why I'm totally wrong.)

**Comment by nikkolasg** [comment] 2017-11-09 11:19
Is is necessary to close it ? Can't we just postpone it, put it in a "Kyber Future Great Work" epic issue of some kind ? 
I imagine it'll be harder to find it again once it's closed, you got to remember the name in 6 months, 1 year ...

**Comment by jeffallen** [comment] 2017-11-13 12:41
Reopening: Still not clear what should be done to improve HideEncode/HideDecode, but because it is only used in curve25519 right now, the current job is to de-clutter the kyber package for v1 by moving Hiding into the curve25519 package somehow.

When that's done we'll close this issue, and if in the future we implement hiding on other curves, we will maybe generalize it.

**Comment by nikkolasg** [comment] 2017-11-13 13:06
Mhhh... Then for code that does use the `Hiding` interface, you will have to cast the points to the `edwards25519.Point` struct ? 
That does not sound good, more like a regression than a progression. Also, the currently on-going PURB project will likely implement and use such an interface. I'm still in favor that we keep it.  But please prove me wrong !

Maybe before coming to a consensus on this subject, may I propose an alternative in the meantime ? This interface can be simply moved to its own file at the top root level, like `hiding.go` so it's more explicit (towards the developer of implementations of that interface and towards the user of the library). We can specify that the interface is likely to change or be merged in the comments if necessary.

**Comment by jeffallen** [comment] 2017-11-20 07:57
Ok, after trying some experiments and reading and thinking some more @nikkolasg has convinced me to go back to not changing anything on this.

**Closed by jeffallen** 2017-11-20 07:57 UTC
